-- ХКООП, база hkoop, utf8mb4
CREATE TABLE IF NOT EXISTS news (
  id VARCHAR(128) PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  date DATE NOT NULL,
  category VARCHAR(64) NOT NULL,
  tags TEXT NOT NULL DEFAULT '[]',
  excerpt TEXT NOT NULL,
  old_url VARCHAR(500) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS documents (
  id VARCHAR(128) PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  type VARCHAR(64) NOT NULL,
  year INT NOT NULL,
  file_old VARCHAR(500) NULL,
  file_local VARCHAR(500) NULL,
  old_url VARCHAR(500) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS partners (
  id VARCHAR(64) PRIMARY KEY,
  name VARCHAR(255) NOT NULL,
  url VARCHAR(500) NOT NULL,
  logo VARCHAR(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS honor (
  id VARCHAR(128) PRIMARY KEY,
  fio VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL DEFAULT '',
  year INT NOT NULL,
  photo VARCHAR(500) NOT NULL DEFAULT '',
  text TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS events (
  id VARCHAR(128) PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  date DATE NOT NULL,
  type VARCHAR(64) NOT NULL,
  old_url VARCHAR(500) NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS site_settings (
  `key` VARCHAR(128) PRIMARY KEY,
  value TEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
